security:
  jwt:
    token:
      secret-key: eW91ci12ZXJ5LXNlY3VyZS1zZWNyZXQ=

server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  security:
    user:
      name: admin
      password: admin
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      type: trace
      stat: debug
      orm:
        jdbc:
          bind: trace
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: true
  # cache:
  #   type: redis
  # redis:
  #   port: 6379
  #   host: localhost
logging:
  logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      total-size-cap: 10GB
      max-history: 10
  file:
    name: logs/app.log
  # level:
  # org.springframework: DEBUG
